version: 0.2

phases:
  install:
    runtime-versions:
      python: 3.8
  pre_build:
    commands:
      - pip install -r requirements.txt
  build:
    commands:
      - python -m pytest tests/
artifacts:
  files:
    - '**/*'